services:
  - name: blog-fullstack-app
    type: web
    env: docker
    startCommand: ./bin/rails server -b 0.0.0.0
    preDeployCommand: bundle exec rake db:migrate
    dockerfilePath: Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: RAILS_MASTER_KEY
        value: ${RAILS_MASTER_KEY}
      - key: REACT_APP_API_URL
        value: ${REACT_APP_API_URL}
      - key: NODE_ENV
        value: ${NODE_ENV}
